Import libraries

In [10]:
import warnings

import cmle
import random
import numpy as np
import pandas as pd
import re
from sklearn.compose import make_column_transformer
from sklearn.dummy import DummyClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier

# Set random seeds for reproducible results across all runs
seed = 42
random.seed(seed)
np.random.seed(seed)
warnings.filterwarnings('ignore')  # Suppress warning messages for cleaner output

Load Data:

In [11]:
train_df = pd.read_csv("proj/data/train.csv")
test_df = pd.read_csv("proj/data/test.csv")

Data Analysis:

In [12]:
train_df.sort_index()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

Replace any "?" with nan values (on the off chance they weren't already replaced with nan)

In [25]:
train_df_nan = train_df.replace("?", np.nan)
test_df_nan = test_df.replace("?", np.nan)
train_df_nan.shape

(7613, 5)

In [26]:
def clean_text(text):
    text = str (text).lower()
    text = re.sub(r'https?://\S+|www\.\S+','',text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.strip()

In [28]:
train_df_nan['clean_text'] = train_df_nan['text'].apply(clean_text)
test_df_nan['clean_text'] = test_df_nan['text'].apply(clean_text)
test_def_nan['clean_location'] = train_df_nan['location'].apply(clean_text)
test_def_nan['clean_location'] = test_df_nan['location'].apply(clean_text)
test_def_nan['clean_Keyword'] = test_df_nan['Keyword'].apply(clean_text)
test_def_nan['clean_Keyword'] = test_df_nan['Keyword'].apply(clean_text)

NameError: name 'test_def_nan' is not defined

In [21]:
train_df_nan.to_csv('bob.csv')

In [8]:
train_df_nan.info()
train_df_nan.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          7613 non-null   int64
 1   keyword     7552 non-null   object
 2   location    5076 non-null   object
 3   text        7613 non-null   object
 4   target      7613 non-null   int64
 5   clean_text  7613 non-null   object
dtypes: int64(2), object(4)
memory usage: 357.0+ KB

                 id      target
count   7613.000000  7613.00000
mean    5441.934848     0.42966
std     3137.116090     0.49506
min        1.000000     0.00000
25%     2734.000000     0.00000
50%     5408.000000     0.00000
75%     8146.000000     1.00000
max    10873.000000     1.00000

In [9]:
dummy_majority = dummyClassifier(strategy='most_frequent')

dummy_majority.fit(x_train, y_train)

pred_majority = dummy_majority.predict(X_val)

NameError: name 'dummyClassifier' is not defined